# Generated by Django 2.2.1 on 2019-05-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
